name: Eleventy Build and Deploy
on:
  push:
    branches: [ "main" ]
    
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
            publish_dir: _site 
            github_token: ${{ secrets.GITHUB_TOKEN }}
